### ISSUE TITLE
`invalid midi: invalid status byte` when parsing LiveEvent from midi clock

### ISSUE THREAD

**Issue by Boscop** [negamartin/midly#16]
When I'm calling `LiveEvent::parse` with a slice containing only midi clock (`[0xF8]` aka `[248]`), it returns `invalid midi: invalid status byte`.
Any idea why? :)

**Comment by kovaxis** [comment]
Sorry about that, parsing system realtime events wasn't properly implemented for `LiveEvent`. Fixed in `0.5.2`.
Also, sorry about the slow response time. Have a good day :D

**Comment by Boscop** [comment]
Thanks :)
