### ISSUE TITLE
Support for CoreMIDI midi message format

### ISSUE THREAD

**Issue by ulzu** [negamartin/midly#19]
Hi. Great work.

It would be nice if midly could parse MIDI messages received live within CoreMIDI framework, which uses uses 32-bit integers instead of 8-bit integers for its MIDI message packets.

**Comment by kovaxis** [comment]
Helllo! Sorry for the late reply.

I am not familiar with the CoreMIDI framework or how are messages encoded in that context.

However, after some quick googling, I believe messages arrive as a single `u32` per message, am I correct? I am basing myself off of this piece of code:

```swift
let words = Mirror(reflecting: packet.words).children
words.forEach { word in
    let uint32 = word.value as! UInt32
    guard uint32 > 0 else { return }
    midiPacket = MidiPacket(
        first: UInt8((uint32 & 0xFF000000) >> 24),
        second: UInt8((uint32 & 0x00FF0000) >> 16),
        third: UInt8((uint32 & 0x0000FF00) >> 8),
        fourth: UInt8(uint32 & 0x000000FF))        
}
```

In this case, CoreMIDI would basically encode a big endian 4-byte buffer in a `uint32`. You can parse this format using `LiveEvent::parse(&int.to_be_bytes())`.

Is my understanding correct?

**Comment by kovaxis** [comment]
I'm assuming it's correct. If it turns out it isn't, please reopen this issue.
