### ISSUE TITLE
Typo: [0, fps[

### ISSUE THREAD

**Issue by liquidhelium** [negamartin/midly#23]
https://github.com/negamartin/midly/blob/816cb2a585b4d5d1fd7aeb0cb35668f21dc00869/src/primitive.rs#L524

I believe it's a typo.

**Comment by kovaxis** [comment]
No, it's exclusive range syntax. It's equivalent to `[0, fps)`. I'm not sure why I used that syntax.
I've changed it to `[0, fps-1]` to make it clearer.
